# This YAML file contains nginx & csi opensds driver objects,
# which are necessary to run nginx with csi opensds driver.

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-sc-opensdsplugin-1
provisioner: csi-opensdsplugin
parameters:

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensdspvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-sc-opensdsplugin-1
